---
site:
  title: Showroom Template Demo
  url: https://github.com/rhpds/showroom_template_nookbag
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui

antora:
  extensions:
    - '@sntke/antora-mermaid-extension'

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    showroom-collection-version: v1.5.6
    guid: abc123
    bastion_public_hostname: bastion.abc123.ocpv00.rhdp.net
    bastion_ssh_user_name: lab-user
    bastion_ssh_password: password
    ssh_user: lab-user
    openshift_console_url: https://console-openshift-console.apps.cluster-abc123.ocpv00.rhdp.net
    openshift_cluster_ingress_domain: apps.cluster-abc123.ocpv00.rhdp.net

output:
  dir: ./www
