---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Terminal
    path: /wetty
    port: 443
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Client App
    url: 'https://datasphere-ui-${USER}-datasphere.${DOMAIN}'
  - name: Gitea
    url: 'https://gitea.${DOMAIN}'
