---
type: showroom

# Set the left column width to 40%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Terminal
    path: /terminal
    port: 443
  - name: Client App
    url: 'https://datasphere-ui-${USER}-datasphere.${DOMAIN}'
  - name: Gitea
    url: 'https://gitea.${DOMAIN}'
